// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfsVTTzpOH_rKfBNFiDeURraKdwGhCGs8',
    appId: '1:682526605847:web:904c79fbe898fd2fad1252',
    messagingSenderId: '682526605847',
    projectId: 'caba-iot',
    authDomain: 'caba-iot.firebaseapp.com',
    storageBucket: 'caba-iot.firebasestorage.app',
    measurementId: 'G-RM49DRDKKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2sQY79LbXtfT8Q0NIydiY2jzaRBg6_Xc',
    appId: '1:682526605847:android:20bdf21f9e15ff28ad1252',
    messagingSenderId: '682526605847',
    projectId: 'caba-iot',
    storageBucket: 'caba-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIQJcZKg6B6KACl-GUbvNHjsrxpxOlimI',
    appId: '1:682526605847:ios:8e1e0434d6cca873ad1252',
    messagingSenderId: '682526605847',
    projectId: 'caba-iot',
    storageBucket: 'caba-iot.firebasestorage.app',
    iosBundleId: 'com.example.penyiramanTanamanOtomatis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIQJcZKg6B6KACl-GUbvNHjsrxpxOlimI',
    appId: '1:682526605847:ios:8e1e0434d6cca873ad1252',
    messagingSenderId: '682526605847',
    projectId: 'caba-iot',
    storageBucket: 'caba-iot.firebasestorage.app',
    iosBundleId: 'com.example.penyiramanTanamanOtomatis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfsVTTzpOH_rKfBNFiDeURraKdwGhCGs8',
    appId: '1:682526605847:web:154b91ff393a9b06ad1252',
    messagingSenderId: '682526605847',
    projectId: 'caba-iot',
    authDomain: 'caba-iot.firebaseapp.com',
    storageBucket: 'caba-iot.firebasestorage.app',
    measurementId: 'G-ZPGX64EMV8',
  );
}
